### ISSUE TITLE
Restructure API routes for other application types

### ISSUE THREAD

**Issue by IanWearsHat** [HackAtUCI/irvinehacks-site#452] opened 2024-12-09 01:52 UTC
![image](https://github.com/user-attachments/assets/9456d7d1-194c-4e91-9dc1-500ff503a1dc)
Workaround is to make other routes with specified RawApplicationData types.

**Comment by taesungh** [comment] 2024-12-09 02:09
I think what we'll need to do in that case is use a concrete model which contains the union of all application fields so that FastAPI recognizes what values should be parsed from the form data. Then inside the route, use the application type as a discriminator to attempt validation on a specific model (see [Discriminated Unions with `str` discriminators](https://docs.pydantic.dev/latest/concepts/unions/#discriminated-unions))

**Comment by taesungh** [comment] 2024-12-09 02:18
Think also duplicate of #448?

**Comment by waalbert** [comment] 2024-12-09 03:02
We've made the decision to add separate routes for mentor and volunteer applications. In the future, we can take a look into combining all the applications into one endpoint.

**Comment by taesungh** [comment] 2024-12-09 04:07
No, I agree: separate routes keeps it clear what data each form needs (e.g. when looking at the auto-generated API documentation for debugging as I often do). Where a discriminator could help is the final step of constructing the `ProcessedApplicationData` object as well as the `Applicant` object.

**Comment by waalbert** [comment] 2024-12-09 04:16
A little bit of misunderstanding earlier. I see what you're saying, and I agree.

**Closed** 2024-12-11 01:03 UTC
